### PR TITLE
Django 1.9 support, tox

### PR DESCRIPTION
**Pull request by teserak**

### CODE REVIEW

**Comment by dmr** [comment]
@dcramer Can this be merged?
@teserak Django 1.9 is stable now so you could adjust your code to the stable version :)

**Comment by b7w** [comment]
@dmr +1

**Comment by dcramer** [comment]
just fyi we're likely abandoning this project as Sentry no longer uses it

**Comment by dmr** [comment]
Thanks for merging, sorry to hear that :(

What were the reasons to drop it?

**Comment by dcramer** [comment]
@dmr we're moving away from being tied to Django, and recently we needed to refactor how our CLI works. We decided to build something internal to Sentry to avoid adding more complexity into Logan itself.

**Comment by dmr** [comment]
@dcramer Thanks for letting us know, I'll look into it if we drop logan also

**Comment by jathanism** [comment]
FWIW I'll happily take over Logan. :)

**Pull request merged**
